name: Update Spotify Counter

on:
  schedule:
    # 19:00 WIB - 03:00 WIB
    # WIB = UTC+7
    - cron: "0,30 12-20 * * *"

  workflow_dispatch:

jobs:
  update-counter:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Playwright
        run: npx playwright install chromium --with-deps

      - name: Restore Spotify Login
        run: |
          cat << 'EOF' > spotify-login.json
          ${{ secrets.SPOTIFY_LOGIN_JSON }}
          EOF

      - name: Run Counter
        run: node generate-counter.js

      - name: Commit updated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add counter.json
          git add spotify-snapshot.json
          git add spotify-history.json

          git diff --staged --quiet || git commit -m "update spotify counter"

          git push
